<a href="https://colab.research.google.com/github/JaCaRego/JaCaRego/blob/main/C%C3%B3pia_de_Revisao_Modulo09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Verificação e Tratamento de Dados Nulos

A verificação e o tratamento de dados nulos (valores ausentes) são etapas cruciais na análise de dados, pois podem distorcer resultados, gerar erros ou limitar a capacidade de extrair insights.

**Por que é importante?**
*   **Precisão:** Valores nulos podem enviesar suas análises estatísticas e modelos preditivos.
*   **Integridade:** Garantir que seus dados são consistentes e completos.
*   **Funcionalidade:** Muitos algoritmos de machine learning não conseguem lidar diretamente com valores nulos.

**Métodos comuns para identificar e tratar dados nulos:**

1.  **Identificação:**
    *   `df.isnull().sum()`: Conta a quantidade de nulos por coluna.
    *   `df.isnull().sum() / len(df)`: Mostra a porcentagem de nulos por coluna.
    *   `df.info()`: Fornece um resumo conciso do DataFrame, incluindo contagens de valores não nulos.

2.  **Tratamento (Imputação/Remoção):**
    *   **Remoção:**
        *   `df.dropna()`: Remove linhas ou colunas que contêm valores nulos. Use com cautela para não perder dados importantes.
    *   **Imputação (Preenchimento):**
        *   `df.fillna(valor)`: Preenche valores nulos com um valor específico (ex: 0, média, mediana, moda).
        *   `df.fillna(df.mean())`: Preenche nulos com a média da coluna (para dados numéricos).
        *   `df.fillna(df.median())`: Preenche nulos com a mediana da coluna (menos sensível a outliers).
        *   `df.fillna(df.mode().iloc[0])`: Preenche nulos com a moda da coluna.
        *   `df.fillna(method='ffill')` ou `df.fillna(method='bfill')`: Preenche nulos usando o valor anterior (`ffill`) ou o próximo (`bfill`) (útil em séries temporais).
        *   **Imputação mais avançada:** Utilização de modelos de machine learning para prever os valores nulos (ex: `IterativeImputer` do `scikit-learn`).

A escolha do método depende do contexto dos seus dados, da quantidade de nulos e do impacto que a imputação ou remoção pode ter na sua análise.

Com este exemplo, pudemos:
*   Identificar nulos e inconsistências.
*   Converter tipos de dados problemáticos (`Quantidade`, `Data_Venda`) usando `pd.to_numeric` e `pd.to_datetime` com `errors='coerce'`.
*   Imputar nulos em colunas numéricas com a média (`Valor_Total`) e mediana (`Quantidade`).
*   Imputar nulos em colunas categóricas com a moda e padronizar textos (`Regiao_Venda`).
*   Utilizar `ffill` para preenchimento sequencial (`Data_Venda`).

Este processo garante que seu DataFrame esteja limpo e pronto para análises mais precisas e robustas.

### Entendendo `errors='coerce'`

O parâmetro `errors='coerce'` é muito útil em funções como `pd.to_numeric()` e `pd.to_datetime()` do pandas. Ele indica como lidar com valores que não podem ser convertidos para o tipo de dado desejado.

Quando você define `errors='coerce'`:

*   **Valores inválidos são convertidos para `NaN` (Not a Number)** para dados numéricos, ou `NaT` (Not a Time) para dados de data/hora.
*   Isso **evita que o programa retorne um erro** (como `ValueError`) e pare a execução ao encontrar um valor que não consegue converter.
*   Em vez de quebrar, os valores problemáticos são 'coagidos' a se tornarem um valor nulo (`NaN` ou `NaT`), permitindo que o restante do DataFrame seja processado. Posteriormente, você pode tratar esses `NaN`s ou `NaT`s com métodos como `fillna()` ou `dropna()`.

**Exemplo:**

Se você tem uma coluna `Quantidade` com valores `[1, 2, 'um', 4]` e tenta converter para numérico sem `errors='coerce'`, o pandas levantará um erro ao encontrar 'um'.

Com `pd.to_numeric(df['Quantidade'], errors='coerce')`, a coluna se tornaria `[1.0, 2.0, NaN, 4.0]`, permitindo que você continue o tratamento dos dados, por exemplo, preenchendo o `NaN` com a mediana ou a média.

### Exemplo Prático de Tratamento

#### Exemplo Prático com `df_vendas`

In [ ]:
import pandas as pd
import numpy as np

# Criando um DataFrame com dados nulos e inconsistentes
data = {
    'ID_Pedido': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Produto': ['Celular', 'Notebook', 'Tablet', 'Fone', 'Smartwatch', 'Celular', 'Tablet', 'Fone', 'Notebook', 'Câmera'],
    'Valor_Total': [1500.0, 3000.0, np.nan, 250.0, 800.0, 1600.0, 750.0, np.nan, 3200.0, 1200.0],
    'Quantidade': [1, 1, 2, 'um', 1, 1, 1, 2, '1', 1],
    'Data_Venda': ['2023-01-01', '02/01/2023', '2023-01-03', '2023-01-04', 'invalid-date', '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10'],
    'Regiao_Venda': ['Sudeste', 'Nordeste', 'Centro-Oeste', 'sudeste', np.nan, 'Sul', 'Nordeste', 'sudeste', 'Sudeste', 'Norte']
}
df_vendas = pd.DataFrame(data)

print('DataFrame Original:')
display(df_vendas)
print('\nInformações do DataFrame Original:')
df_vendas.info()
print('\nValores nulos por coluna (original):')
print(df_vendas.isnull().sum())

DataFrame Original:

   ID_Pedido     Produto  Valor_Total Quantidade    Data_Venda  Regiao_Venda
0        101     Celular       1500.0          1    2023-01-01       Sudeste
1        102    Notebook       3000.0          1    02/01/2023      Nordeste
2        103      Tablet          NaN          2    2023-01-03  Centro-Oeste
3        104        Fone        250.0         um    2023-01-04       sudeste
4        105  Smartwatch        800.0          1  invalid-date           NaN
5        106     Celular       1600.0          1    2023-01-06           Sul
6        107      Tablet        750.0          1    2023-01-07      Nordeste
7        108        Fone          NaN          2    2023-01-08       sudeste
8        109    Notebook       3200.0          1    2023-01-09       Sudeste
9        110      Câmera       1200.0          1    2023-01-10         Norte

Informações do DataFrame Original:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID_Pedido     10 non-null     int64
 1   Produto       10 non-null     object
 2   Valor_Total   8 non-null      float64
 3   Quantidade    10 non-null     object
 4   Data_Venda    10 non-null     object
 5   Regiao_Venda  9 non-null      object
dtypes: float64(1), int64(1), object(4)
memory usage: 612.0+ bytes

Valores nulos por coluna (original):
ID_Pedido       0
Produto         0
Valor_Total     2
Quantidade      0
Data_Venda      0
Regiao_Venda    1
dtype: int64

#### Tratamento 1: Conversão de Tipos e Preenchimento Básico

In [ ]:
# 1. Tratamento da coluna 'Quantidade': converter para numérico, erros viram NaN
# 'um' e '1' serão tratados. 'um' vira NaN, '1' vira 1.
df_vendas['Quantidade'] = pd.to_numeric(df_vendas['Quantidade'], errors='coerce')

# 2. Tratamento da coluna 'Data_Venda': converter para datetime, erros viram NaT
# 'invalid-date' vira NaT (NaN para datas).
df_vendas['Data_Venda'] = pd.to_datetime(df_vendas['Data_Venda'], errors='coerce')

# Exibindo o estado atual para ver os Nulos após a conversão
print('DataFrame após conversão de tipos:')
display(df_vendas)
print('\nValores nulos por coluna (após conversão):')
print(df_vendas.isnull().sum())

NameError: name 'df_vendas' is not defined

#### Tratamento 2: Imputação de Nulos com Média, Mediana, Moda e FFill

In [ ]:
# 3. Tratamento da coluna 'Valor_Total': preencher nulos com a média
media_valor_total = df_vendas['Valor_Total'].mean()
df_vendas['Valor_Total'] = df_vendas['Valor_Total'].fillna(media_valor_total)

# 4. Preencher nulos em 'Quantidade' (resultantes do 'um' e outros) com a mediana
mediana_quantidade = df_vendas['Quantidade'].median()
df_vendas['Quantidade'] = df_vendas['Quantidade'].fillna(mediana_quantidade)

# 5. Tratamento da coluna 'Regiao_Venda': padronizar valores e preencher nulos com a moda (valor mais frequente)
df_vendas['Regiao_Venda'] = df_vendas['Regiao_Venda'].str.capitalize() # Padroniza 'sudeste' para 'Sudeste'
moda_regiao = df_vendas['Regiao_Venda'].mode()[0]
df_vendas['Regiao_Venda'] = df_vendas['Regiao_Venda'].fillna(moda_regiao)

# 6. Preencher nulos em 'Data_Venda' (do 'invalid-date') usando o método ffill (forward fill)
# ffill preenche com o valor válido anterior na coluna.
df_vendas['Data_Venda'] = df_vendas['Data_Venda'].fillna(method='ffill')

print('\nDataFrame Final Tratado:')
display(df_vendas)
print('\nValores nulos por coluna (final):')
print(df_vendas.isnull().sum())
print('\nInformações do DataFrame Final Tratado:')
df_vendas.info()

NameError: name 'df_vendas' is not defined

### Normalização e Padronização de Dados

Normalização e padronização são técnicas de pré-processamento de dados usadas para transformar variáveis numéricas, de modo que fiquem em uma escala semelhante. Isso é crucial para muitos algoritmos de Machine Learning, pois eles podem ter um desempenho ruim se as características de entrada tiverem escalas muito diferentes.

**1. Normalização (Min-Max Scaling):**
*   **Objetivo:** Redimensionar os valores para um intervalo fixo, geralmente entre 0 e 1.
*   **Fórmula:** `X_normalized = (X - X_min) / (X_max - X_min)`
*   **Quando usar:** Quando a distribuição dos dados não é Gaussiana (não segue uma curva de sino) e você quer valores limitados a um intervalo específico. É sensível a outliers.
*   **Principal Ferramenta:** `sklearn.preprocessing.MinMaxScaler`

**2. Padronização (Standardization):**
*   **Objetivo:** Transformar os dados para que tenham uma média de 0 e um desvio padrão de 1 (distribuição normal padrão).
*   **Fórmula:** `X_standardized = (X - média) / desvio_padrão`
*   **Quando usar:** Quando a distribuição dos dados é aproximadamente Gaussiana ou quando seu algoritmo assume que os dados seguem uma distribuição normal (ex: SVM, Regressão Logística, K-means). É menos sensível a outliers do que a normalização.
*   **Principal Ferramenta:** `sklearn.preprocessing.StandardScaler`

**Por que usar?**
*   **Melhora o desempenho do modelo:** Muitos algoritmos de ML convergem mais rapidamente e performam melhor com dados escalonados.
*   **Evita viés:** Garante que nenhuma característica domine as outras apenas por ter uma escala maior.

**Observação:** Ambas as técnicas devem ser aplicadas **apenas a colunas numéricas** e, idealmente, **após o tratamento de nulos**.

In [ ]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler, LabelEncoder, OneHotEncoder
import pandas as pd
import numpy as np

# --- 0. Recriação do DataFrame para garantir um ponto de partida consistente ---
# Define os dados brutos com nulos e inconsistências para demonstração.
data = {
    'ID_Pedido': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Produto': ['Celular', 'Notebook', 'Tablet', 'Fone', 'Smartwatch', 'Celular', 'Tablet', 'Fone', 'Notebook', 'Câmera'],
    'Valor_Total': [1500.0, 3000.0, np.nan, 250.0, 800.0, 1600.0, 750.0, np.nan, 3200.0, 1200.0], # np.nan representa valores nulos
    'Quantidade': [1, 1, 2, 'um', 1, 1, 1, 2, '1', 1], # 'um' é inconsistente, '1' é string numérica
    'Data_Venda': ['2023-01-01', '02/01/2023', '2023-01-03', '2023-01-04', 'invalid-date', '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10'], # 'invalid-date' é inconsistente
    'Regiao_Venda': ['Sudeste', 'Nordeste', 'Centro-Oeste', 'sudeste', np.nan, 'Sul', 'Nordeste', 'sudeste', 'Sudeste', 'Norte'], # 'sudeste' minúsculo e np.nan
    'Prioridade': ['Alta', 'Média', 'Baixa', 'Média', 'Alta', 'Baixa', 'Média', 'Alta', 'Baixa', 'Média'] # Nova coluna categórica ordinal para exemplo de Label Encoding
}
df_vendas_original = pd.DataFrame(data) # Cria o DataFrame a partir do dicionário de dados.

# --- 0.1 Tratamento de Nulos e Inconsistências Básicas (Pré-processamento para Escalamento/Codificação) ---
# Converte a coluna 'Quantidade' para tipo numérico, transformando erros ('um') em NaN.
df_vendas_original['Quantidade'] = pd.to_numeric(df_vendas_original['Quantidade'], errors='coerce')
# Preenche os valores nulos em 'Valor_Total' (np.nan) com a média da própria coluna.
df_vendas_original['Valor_Total'] = df_vendas_original['Valor_Total'].fillna(df_vendas_original['Valor_Total'].mean())
# Preenche os valores nulos em 'Quantidade' (que vieram de 'um') com a mediana da coluna, pois é menos sensível a outliers que a média.
df_vendas_original['Quantidade'] = df_vendas_original['Quantidade'].fillna(df_vendas_original['Quantidade'].median())

# Padroniza os valores da coluna 'Regiao_Venda' (ex: 'sudeste' vira 'Sudeste').
df_vendas_original['Regiao_Venda'] = df_vendas_original['Regiao_Venda'].str.capitalize()
# Calcula a moda (valor mais frequente) da coluna 'Regiao_Venda'.
moda_regiao = df_vendas_original['Regiao_Venda'].mode()[0]
# Preenche os valores nulos em 'Regiao_Venda' com a moda calculada.
df_vendas_original['Regiao_Venda'] = df_vendas_original['Regiao_Venda'].fillna(moda_regiao)

print("--- DataFrame Original Após Tratamento de Nulos e Inconsistências Básicas ---")
display(df_vendas_original.head()) # Exibe as primeiras linhas do DataFrame tratado.
print(df_vendas_original[['Valor_Total', 'Quantidade', 'Regiao_Venda', 'Prioridade']].describe(include='all')) # Descreve as estatísticas das colunas relevantes.

# --- Seleção de Colunas para Escalamento e Codificação ---
features_numericas_para_escalar = ['Valor_Total', 'Quantidade'] # Colunas numéricas para aplicar escalonadores.
feature_categorica_label = 'Prioridade' # Coluna categórica para Label Encoding (ordinal).
feature_categorica_onehot = 'Regiao_Venda' # Coluna categórica para One-Hot Encoding (nominal).

# --- Criando cópias do DataFrame para demonstrar cada técnica separadamente ---
# Isso evita que uma transformação afete a próxima demonstração.
df_normalizado = df_vendas_original.copy()
df_padronizado = df_vendas_original.copy()
df_robust = df_vendas_original.copy()
df_label_encoded = df_vendas_original.copy()
df_onehot_encoded = df_vendas_original.copy()

# --- 1. Normalização (Min-Max Scaling) ---
# Inicializa o scaler Min-Max.
scaler_minmax = MinMaxScaler()
# Aplica a transformação: ajusta o scaler aos dados e depois os transforma para o intervalo [0, 1].
df_normalizado[features_numericas_para_escalar] = scaler_minmax.fit_transform(df_normalizado[features_numericas_para_escalar])

print("\n--- DataFrame Normalizado (Min-Max Scaling) ---")
display(df_normalizado[features_numericas_para_escalar].head()) # Exibe as primeiras linhas das colunas escalonadas.
print(df_normalizado[features_numericas_para_escalar].describe()) # Mostra estatísticas (min e max próximos de 0 e 1).

# --- 2. Padronização (Standardization) ---
# Inicializa o scaler Padrão.
scaler_standard = StandardScaler()
# Aplica a transformação: ajusta o scaler aos dados e depois os transforma para ter média 0 e desvio padrão 1.
df_padronizado[features_numericas_para_escalar] = scaler_standard.fit_transform(df_padronizado[features_numericas_para_escalar])

print("\n--- DataFrame Padronizado (Standardization) ---")
display(df_padronizado[features_numericas_para_escalar].head()) # Exibe as primeiras linhas das colunas escalonadas.
print(df_padronizado[features_numericas_para_escalar].describe()) # Mostra estatísticas (média próxima de 0, std dev próxima de 1).

# --- 3. Robust Scaling (Escalonamento Robusto) ---
# Inicializa o RobustScaler.
scaler_robust = RobustScaler()
# Aplica a transformação: ajusta o scaler usando mediana e IQR, depois os transforma.
df_robust[features_numericas_para_escalar] = scaler_robust.fit_transform(df_robust[features_numericas_para_escalar])

print("\n--- DataFrame Robusto (Robust Scaling) ---")
display(df_robust[features_numericas_para_escalar].head()) # Exibe as primeiras linhas das colunas escalonadas.
print(df_robust[features_numericas_para_escalar].describe()) # Mostra estatísticas (mediana próxima de 0).

# --- Codificação de Variáveis Categóricas ---

# --- 4. Label Encoding (Codificação de Rótulos) ---
# Inicializa o LabelEncoder.
encoder_label = LabelEncoder()
# Aplica a codificação: ajusta o encoder às categorias únicas e as transforma em inteiros.
df_label_encoded[feature_categorica_label + '_Encoded'] = encoder_label.fit_transform(df_label_encoded[feature_categorica_label])

print(f"\n--- DataFrame com '{feature_categorica_label}' (Label Encoded) ---")
display(df_label_encoded[[feature_categorica_label, feature_categorica_label + '_Encoded']].head()) # Exibe a coluna original e a codificada.
print(f"Classes originais mapeadas para números: {encoder_label.classes_}") # Mostra o mapeamento realizado pelo encoder.

# --- 5. One-Hot Encoding (Codificação One-Hot) ---
# Utiliza pd.get_dummies para aplicar One-Hot Encoding. É mais direto para DataFrames.
# 'columns' especifica qual coluna deve ser codificada.
# 'prefix' adiciona um prefixo às novas colunas para identificação.
df_onehot_encoded = pd.get_dummies(df_onehot_encoded, columns=[feature_categorica_onehot], prefix=feature_categorica_onehot)

print(f"\n--- DataFrame com '{feature_categorica_onehot}' (One-Hot Encoded) ---")
# Filtra e exibe apenas as colunas criadas pelo One-Hot Encoding.
display(df_onehot_encoded.filter(like=feature_categorica_onehot).head())

print("\nObserve como cada técnica transforma os dados de maneiras diferentes, adequadas para distintos cenários de modelagem.")

--- DataFrame Original Após Tratamento de Nulos e Inconsistências Básicas ---

,ID_Pedido,Produto,Valor_Total,Quantidade,Data_Venda,Regiao_Venda,Prioridade
0,101,Celular,1500.0,1.0,2023-01-01,Sudeste,Alta
1,102,Notebook,3000.0,1.0,02/01/2023,Nordeste,Média
2,103,Tablet,1537.5,2.0,2023-01-03,Centro-oeste,Baixa
3,104,Fone,250.0,1.0,2023-01-04,Sudeste,Média
4,105,Smartwatch,800.0,1.0,invalid-date,Sudeste,Alta

        Valor_Total  Quantidade Regiao_Venda Prioridade
count     10.000000   10.000000           10         10
unique          NaN         NaN            5          3
top             NaN         NaN      Sudeste      Média
freq            NaN         NaN            5          4
mean    1537.500000    1.200000          NaN        NaN
std      933.556521    0.421637          NaN        NaN
min      250.000000    1.000000          NaN        NaN
25%      900.000000    1.000000          NaN        NaN
50%     1518.750000    1.000000          NaN        NaN
75%     1584.375000    1.000000          NaN        NaN
max     3200.000000    2.000000          NaN        NaN

--- DataFrame Normalizado (Min-Max Scaling) ---

   Valor_Total  Quantidade
0     0.423729         0.0
1     0.932203         0.0
2     0.436441         1.0
3     0.000000         0.0
4     0.186441         0.0

       Valor_Total  Quantidade
count    10.000000   10.000000
mean      0.436441    0.200000
std       0.316460    0.421637
min       0.000000    0.000000
25%       0.220339    0.000000
50%       0.430085    0.000000
75%       0.452331    0.000000
max       1.000000    1.000000

--- DataFrame Padronizado (Standardization) ---

   Valor_Total  Quantidade
0    -0.042342        -0.5
1     1.651331        -0.5
2     0.000000         2.0
3    -1.453735        -0.5
4    -0.832722        -0.5

        Valor_Total    Quantidade
count  1.000000e+01  1.000000e+01
mean  -5.551115e-18  6.661338e-17
std    1.054093e+00  1.054093e+00
min   -1.453735e+00 -5.000000e-01
25%   -7.198107e-01 -5.000000e-01
50%   -2.117090e-02 -5.000000e-01
75%    5.292726e-02 -5.000000e-01
max    1.877153e+00  2.000000e+00

--- DataFrame Robusto (Robust Scaling) ---

   Valor_Total  Quantidade
0    -0.027397         0.0
1     2.164384         0.0
2     0.027397         1.0
3    -1.853881         0.0
4    -1.050228         0.0

       Valor_Total  Quantidade
count    10.000000   10.000000
mean      0.027397    0.200000
std       1.364101    0.421637
min      -1.853881    0.000000
25%      -0.904110    0.000000
50%       0.000000    0.000000
75%       0.095890    0.000000
max       2.456621    1.000000

--- DataFrame com 'Prioridade' (Label Encoded) ---

  Prioridade  Prioridade_Encoded
0       Alta                   0
1      Média                   2
2      Baixa                   1
3      Média                   2
4       Alta                   0

Classes originais mapeadas para números: ['Alta' 'Baixa' 'Média']

--- DataFrame com 'Regiao_Venda' (One-Hot Encoded) ---

,Regiao_Venda_Centro-oeste,Regiao_Venda_Nordeste,Regiao_Venda_Norte,Regiao_Venda_Sudeste,Regiao_Venda_Sul
0,False,False,False,True,False
1,False,True,False,False,False
2,True,False,False,False,False
3,False,False,False,True,False
4,False,False,False,True,False

Observe como cada técnica transforma os dados de maneiras diferentes, adequadas para distintos cenários de modelagem.

### Resumo dos Métodos de Pré-processamento

**1. Normalização (Min-Max Scaling):**
*   **Vantagens:** Reduz os dados para um intervalo fixo (geralmente [0, 1]), útil para algoritmos que usam distâncias. Preserva a forma da distribuição original.
*   **Melhor Aplicabilidade:** Dados com distribuição não Gaussiana, ou quando é preciso um intervalo de valores bem definido (ex: redes neurais que esperam entradas entre 0 e 1).
*   **Desvantagens:** Muito sensível a outliers, que podem distorcer o intervalo e comprimir a maioria dos dados.

**2. Padronização (Standardization):**
*   **Vantagens:** Transforma os dados para ter média 0 e desvio padrão 1, sendo menos sensível a outliers do que Min-Max Scaling.
*   **Melhor Aplicabilidade:** Dados com distribuição aproximadamente Gaussiana, ou algoritmos que assumem essa distribuição (ex: SVM, Regressão Logística, K-Means).
*   **Desvantagens:** Não garante um intervalo de valores específico, e os valores transformados podem ser difíceis de interpretar diretamente.

**3. Robust Scaling (Escalonamento Robusto):**
*   **Vantagens:** Altamente robusto a outliers, pois utiliza mediana e o Intervalo Interquartil (IQR).
*   **Melhor Aplicabilidade:** Dados com muitos outliers conhecidos, onde você não quer que esses valores extremos distorçam a escala da maioria dos dados.
*   **Desvantagens:** Pode ser menos eficaz se outliers não forem um problema significativo ou se a distribuição for muito assimétrica e a robustez não for prioritária.

#TRATAMENTO DE VARIÁVEIS CATEGÓRICAS

**4. Label Encoding (Codificação de Rótulos):**
*   **Vantagens:** Simples de implementar e eficiente em termos de espaço.
*   **Melhor Aplicabilidade:** Variáveis categóricas ordinais, onde a ordem entre as categorias tem significado (ex: 'Pequeno', 'Médio', 'Grande').
*   **Desvantagens:** Introduz uma ordem artificial em variáveis nominais (sem ordem intrínseca), o que pode enganar algoritmos e levar a interpretações errôneas.
* O que faz: Atribui um número inteiro único para cada categoria. Por exemplo, 'Baixa' = 0, 'Média' = 1, 'Alta' = 2.
Vantagens: Simples e economiza espaço.
* Melhor Aplicabilidade: Quando há uma ordem natural entre as categorias (variáveis ordinais), como 'Prioridade' no nosso exemplo.
Desvantagens: Pode introduzir uma ordem artificial que o modelo pode interpretar erroneamente se a variável não for realmente ordinal.

**5. One-Hot Encoding (Codificação One-Hot):**
*   **Vantagens:** Evita a introdução de uma ordem artificial, ideal para variáveis categóricas nominais (sem ordem intrínseca).
*   **Melhor Aplicabilidade:** Variáveis categóricas nominais e quando o número de categorias não é excessivamente grande.
*   **Desvantagens:** Cria muitas colunas novas (aumenta a dimensionalidade), o que pode ser computacionalmente custoso e levar à "maldição da dimensionalidade" ou multicolinearidade.
* O que faz: Cria uma nova coluna binária para cada categoria única. A coluna correspondente à categoria presente recebe '1' e as outras '0'. Por exemplo, 'Sudeste' se torna Regiao_Venda_Sudeste = 1, Regiao_Venda_Nordeste = 0, etc.
Vantagens: Evita que o modelo assuma uma ordem entre categorias que não existe, sendo ideal para variáveis nominais.
* Melhor Aplicabilidade: Para variáveis categóricas nominais (sem ordem intrínseca), como 'Regiao_Venda' no nosso exemplo, e quando o número de categorias não é muito grande.
Desvantagens: Pode criar muitas colunas novas, aumentando a dimensionalidade dos dados ('maldição da dimensionalidade').

### Engenharia de Features (Feature Engineering)

A Engenharia de Features é o processo de criar novas variáveis (features) a partir de dados existentes, ou transformar features existentes, para melhorar o desempenho de modelos de Machine Learning. É uma etapa crucial no pipeline de análise de dados e modelagem, pois a qualidade e a relevância das features impactam diretamente a capacidade do modelo de aprender e fazer previsões precisas.

**Por que a Engenharia de Features é importante?**
*   **Melhora o desempenho do modelo:** Features bem construídas podem revelar padrões e relações nos dados que as features originais não mostravam.
*   **Simplifica o modelo:** Em alguns casos, boas features podem tornar um problema complexo mais simples para o modelo resolver.
*   **Aumenta a interpretabilidade:** Novas features podem fornecer insights mais claros sobre os fatores que influenciam o resultado.

**Técnicas Comuns de Engenharia de Features:**

1.  **Extração de Componentes de Data/Hora:** A partir de uma coluna de data/hora, é possível extrair:
    *   Ano, Mês, Dia
    *   Dia da semana, Dia do ano
    *   Hora, Minuto, Segundo
    *   Indicadores como `is_weekend`, `is_holiday`.

2.  **Combinação de Features:** Criar novas features combinando duas ou mais existentes.
    *   Ex: `Preco_Unitario = Valor_Total / Quantidade`
    *   Ex: `Lucro = Vendas - Custo`

3.  **Agregação de Features:** Sumarizar informações de grupos de dados.
    *   Ex: Média de vendas por `Produto` ou `Regiao_Venda`.

4.  **Transformações:** Aplicar funções matemáticas para mudar a distribuição de uma feature.
    *   Ex: `log(x)`, `sqrt(x)` para reduzir a assimetria ou lidar com dados com grandes variações.

5.  **Criação de Flags Binárias:** Criar colunas 0/1 para indicar a presença de uma condição.
    *   Ex: `has_discount`, `is_promotion`.

**Boas Práticas:**
*   **Conhecimento do Domínio:** Entender o negócio ou o problema ajuda a criar features mais relevantes.
*   **Iteração:** A engenharia de features é um processo iterativo; crie, teste, avalie e refine.
*   **Evitar Vazamento de Dados (Data Leakage):** Certifique-se de que as features não contêm informações do futuro ou do resultado que o modelo deve prever.
*   **Manter a interpretabilidade:** Nem sempre a feature mais complexa é a melhor; features mais simples e interpretáveis são preferíveis quando possível.

### Exemplo Prático de Engenharia de Features

Vamos aplicar algumas técnicas de Engenharia de Features no `df_vendas` tratado.

In [ ]:
import pandas as pd
import numpy as np

# --- Recriação do DataFrame df_vendas a partir dos dados originais e pré-processado para o ponto inicial da FE ---
# Garante que o DataFrame esteja limpo de nulos e com tipos corretos antes da FE.
data = {
    'ID_Pedido': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Produto': ['Celular', 'Notebook', 'Tablet', 'Fone', 'Smartwatch', 'Celular', 'Tablet', 'Fone', 'Notebook', 'Câmera'],
    'Valor_Total': [1500.0, 3000.0, np.nan, 250.0, 800.0, 1600.0, 750.0, np.nan, 3200.0, 1200.0],
    'Quantidade': [1, 1, 2, 'um', 1, 1, 1, 2, '1', 1],
    'Data_Venda': ['2023-01-01', '02/01/2023', '2023-01-03', '2023-01-04', 'invalid-date', '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10'],
    'Regiao_Venda': ['Sudeste', 'Nordeste', 'Centro-Oeste', 'sudeste', np.nan, 'Sul', 'Nordeste', 'sudeste', 'Sudeste', 'Norte']
}
df_vendas_fe = pd.DataFrame(data)

# Aplicando o pré-processamento de nulos e inconsistências como feito anteriormente
df_vendas_fe['Quantidade'] = pd.to_numeric(df_vendas_fe['Quantidade'], errors='coerce')
df_vendas_fe['Valor_Total'] = df_vendas_fe['Valor_Total'].fillna(df_vendas_fe['Valor_Total'].mean())
df_vendas_fe['Quantidade'] = df_vendas_fe['Quantidade'].fillna(df_vendas_fe['Quantidade'].median())

df_vendas_fe['Regiao_Venda'] = df_vendas_fe['Regiao_Venda'].str.capitalize()
moda_regiao = df_vendas_fe['Regiao_Venda'].mode()[0]
df_vendas_fe['Regiao_Venda'] = df_vendas_fe['Regiao_Venda'].fillna(moda_regiao)

df_vendas_fe['Data_Venda'] = pd.to_datetime(df_vendas_fe['Data_Venda'], errors='coerce')
df_vendas_fe['Data_Venda'] = df_vendas_fe['Data_Venda'].fillna(method='ffill')

print("--- DataFrame Após Tratamento de Nulos (Base para Engenharia de Features) ---")
display(df_vendas_fe.head())
print(df_vendas_fe.info())

# --- 1. Extração de Componentes de Data/Hora ---
# Cria uma nova feature para o Ano da Venda, extraindo do campo 'Data_Venda'.
df_vendas_fe['Ano_Venda'] = df_vendas_fe['Data_Venda'].dt.year
# Cria uma nova feature para o Mês da Venda.
df_vendas_fe['Mes_Venda'] = df_vendas_fe['Data_Venda'].dt.month
# Cria uma nova feature para o Dia da Semana (0=Segunda, 6=Domingo).
df_vendas_fe['Dia_Semana_Venda'] = df_vendas_fe['Data_Venda'].dt.dayofweek
# Cria uma flag binária indicando se a venda ocorreu no fim de semana (Sábado ou Domingo).
df_vendas_fe['is_Fim_Semana'] = df_vendas_fe['Dia_Semana_Venda'].apply(lambda x: 1 if x >= 5 else 0)

# --- 2. Combinação de Features ---
# Calcula o Preço Unitário de cada produto. Adiciona um tratamento para evitar divisão por zero, caso Quantidade seja 0.
df_vendas_fe['Preco_Unitario'] = df_vendas_fe.apply(lambda row: row['Valor_Total'] / row['Quantidade'] if row['Quantidade'] > 0 else 0, axis=1)

# --- 3. Agregação de Features (exemplo simples) ---
# Calcula a média de Valor_Total por Produto. Este é um exemplo de feature agregada que pode ser juntada ao DataFrame original.
media_valor_por_produto = df_vendas_fe.groupby('Produto')['Valor_Total'].transform('mean')
df_vendas_fe['Media_Valor_Produto'] = media_valor_por_produto

print("\n--- DataFrame Após Engenharia de Features ---")
display(df_vendas_fe.head())
print(df_vendas_fe.info())
print(df_vendas_fe[['Data_Venda', 'Ano_Venda', 'Mes_Venda', 'Dia_Semana_Venda', 'is_Fim_Semana', 'Valor_Total', 'Quantidade', 'Preco_Unitario', 'Media_Valor_Produto']].head())

print("\nAs novas features criadas ('Ano_Venda', 'Mes_Venda', 'Dia_Semana_Venda', 'is_Fim_Semana', 'Preco_Unitario', 'Media_Valor_Produto') agora enriquecem o DataFrame e podem ser utilizadas em modelos de Machine Learning.")

--- DataFrame Após Tratamento de Nulos (Base para Engenharia de Features) ---

/tmp/ipykernel_290/2382668582.py:26: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_vendas_fe['Data_Venda'] = df_vendas_fe['Data_Venda'].fillna(method='ffill')

   ID_Pedido     Produto  Valor_Total  Quantidade Data_Venda  Regiao_Venda
0        101     Celular       1500.0         1.0 2023-01-01       Sudeste
1        102    Notebook       3000.0         1.0 2023-01-01      Nordeste
2        103      Tablet       1537.5         2.0 2023-01-03  Centro-oeste
3        104        Fone        250.0         1.0 2023-01-04       Sudeste
4        105  Smartwatch        800.0         1.0 2023-01-04       Sudeste

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID_Pedido     10 non-null     int64
 1   Produto       10 non-null     object
 2   Valor_Total   10 non-null     float64
 3   Quantidade    10 non-null     float64
 4   Data_Venda    10 non-null     datetime64[ns]
 5   Regiao_Venda  10 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(1), object(2)
memory usage: 612.0+ bytes
None

--- DataFrame Após Engenharia de Features ---

,ID_Pedido,Produto,Valor_Total,Quantidade,Data_Venda,Regiao_Venda,Ano_Venda,Mes_Venda,Dia_Semana_Venda,is_Fim_Semana,Preco_Unitario,Media_Valor_Produto
0,101,Celular,1500.0,1.0,2023-01-01,Sudeste,2023,1,6,1,1500.00,1550.00
1,102,Notebook,3000.0,1.0,2023-01-01,Nordeste,2023,1,6,1,3000.00,3100.00
2,103,Tablet,1537.5,2.0,2023-01-03,Centro-oeste,2023,1,1,0,768.75,1143.75
3,104,Fone,250.0,1.0,2023-01-04,Sudeste,2023,1,2,0,250.00,893.75
4,105,Smartwatch,800.0,1.0,2023-01-04,Sudeste,2023,1,2,0,800.00,800.00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID_Pedido            10 non-null     int64
 1   Produto              10 non-null     object
 2   Valor_Total          10 non-null     float64
 3   Quantidade           10 non-null     float64
 4   Data_Venda           10 non-null     datetime64[ns]
 5   Regiao_Venda         10 non-null     object
 6   Ano_Venda            10 non-null     int32
 7   Mes_Venda            10 non-null     int32
 8   Dia_Semana_Venda     10 non-null     int32
 9   is_Fim_Semana        10 non-null     int64
 10  Preco_Unitario       10 non-null     float64
 11  Media_Valor_Produto  10 non-null     float64
dtypes: datetime64[ns](1), float64(4), int32(3), int64(2), object(2)
memory usage: 972.0+ bytes
None
  Data_Venda  Ano_Venda  Mes_Venda  Dia_Semana_Venda  is_Fim_Semana  \
0 2023-01-01       2023          1                 6              1
1 2023-01-01       2023          1                 6              1
2 2023-01-03       2023          1                 1              0
3 2023-01-04       2023          1                 2              0
4 2023-01-04       2023          1                 2              0

   Valor_Total  Quantidade  Preco_Unitario  Media_Valor_Produto
0       1500.0         1.0         1500.00              1550.00
1       3000.0         1.0         3000.00              3100.00
2       1537.5         2.0          768.75              1143.75
3        250.0         1.0          250.00               893.75
4        800.0         1.0          800.00               800.00

As novas features criadas ('Ano_Venda', 'Mes_Venda', 'Dia_Semana_Venda', 'is_Fim_Semana', 'Preco_Unitario', 'Media_Valor_Produto') agora enriquecem o DataFrame e podem ser utilizadas em modelos de Machine Learning.