<a href="https://colab.research.google.com/github/JaCaRego/JaCaRego/blob/main/Modulo09_Python_Preparacao_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Engenharia de Features

A **Engenharia de Features** é o processo de usar o conhecimento do domínio para criar variáveis (features) a partir de dados brutos que tornam os algoritmos de aprendizado de máquina mais eficazes. Basicamente, é transformar os dados existentes para extrair informações mais relevantes para o modelo.

### Principais Ferramentas e Técnicas:

1.  **Transformação de Variáveis Categóricas:**
    *   **One-Hot Encoding:** Converte variáveis categóricas em um formato numérico que pode ser fornecido a algoritmos de ML. Cria novas colunas indicando a presença (1) ou ausência (0) de cada categoria.
    *   **Label Encoding:** Atribui um valor numérico único a cada categoria. Pode ser útil para variáveis ordinais, mas cuidado para não introduzir uma ordem artificial.

2.  **Tratamento de Dados Numéricos:**
    *   **Padronização (Standardization - StandardScaler):** Ajusta os dados para que tenham média zero e desvio padrão um. Útil para algoritmos que são sensíveis à escala das features (ex: SVM, Regressão Logística).
    *   **Normalização (Normalization - MinMaxScaler):** Redimensiona os dados para um intervalo fixo, geralmente entre 0 e 1. Útil para algoritmos que usam distâncias como medida (ex: KNN).
    *   **Binning (Discretização):** Converte variáveis numéricas contínuas em variáveis categóricas, dividindo-as em "caixas" ou intervalos.

3.  **Criação de Novas Features:**
    *   **Interações de Features:** Combinar duas ou mais features existentes para criar uma nova. Por exemplo, "idade x salário" ou "comprimento x largura".
    *   **Features Polinomiais:** Criar potências de features existentes (ex: x, x², x³). Ajuda a capturar relações não lineares.
    *   **Features Baseadas em Tempo:** Extrair informações de datas e horas, como dia da semana, mês, ano, trimestre, feriado, etc.
    *   **Agregações:** Resumir dados por grupos (ex: média de vendas por produto, contagem de eventos por usuário).

4.  **Redução de Dimensionalidade:**
    *   **Análise de Componentes Principais (PCA):** Transforma um conjunto de features correlacionadas em um conjunto menor de componentes não correlacionados (componentes principais), mantendo a maior parte da variância dos dados.
    *   **Seleção de Features (Feature Selection):** Escolher um subconjunto das features mais relevantes para o modelo, descartando as menos importantes. Pode ser feito por métodos estatísticos (ANOVA, Qui-quadrado), modelos (Embedded Methods) ou wrappers (RFE).

5.  **Tratamento de Valores Ausentes:**
    *   **Imputação:** Preencher valores ausentes com a média, mediana, moda, ou usando modelos preditivos.
    *   **Remoção:** Remover linhas ou colunas que contêm valores ausentes (com cautela, para não perder dados importantes).

As ferramentas mais comuns para realizar a engenharia de features em Python incluem:

*   **Pandas:** Para manipulação e transformação de dados em DataFrames.
*   **Scikit-learn (sklearn):** Oferece uma vasta gama de pré-processadores, transformadores e seletores de features (ex: `StandardScaler`, `MinMaxScaler`, `OneHotEncoder`, `LabelEncoder`, `PolynomialFeatures`, `PCA`, `SelectKBest`).
*   **NumPy:** Para operações numéricas eficientes.
*   **Feature-engine:** Uma biblioteca focada exclusivamente em engenharia de features, oferecendo transformadores mais avançados e personalizáveis.

A engenharia de features é muitas vezes a etapa mais importante no desenvolvimento de um modelo de ML, pois a qualidade e relevância das features impactam diretamente o desempenho do modelo.

### 1. Label Encoding

**O que é?**

`Label Encoding` é uma técnica de pré-processamento usada para converter rótulos categóricos em um formato numérico. Cada categoria única em uma coluna é atribuída a um número inteiro exclusivo.

**Quando usar?**

*   É mais apropriado para variáveis categóricas ordinais, ou seja, aquelas que possuem uma ordem intrínseca (ex: 'Pequeno', 'Médio', 'Grande').
*   Pode ser usado para variáveis nominais (sem ordem) quando o número de categorias é muito grande e `One-Hot Encoding` criaria muitas colunas, mas com a ressalva de que pode introduzir uma ordem artificial que o modelo pode interpretar erroneamente.

**Vantagens:**

*   Simples de implementar.
*   Não aumenta a dimensionalidade do **dataset** (conjunto de dados - uma coleção de dados relacionados, geralmente organizada em tabelas) (ao contrário do `One-Hot Encoding`).

**Desvantagens:**

*   Para variáveis nominais, a atribuição de números inteiros pode levar o modelo a assumir uma relação ordinal ou de magnitude entre as categorias, o que pode prejudicar o desempenho do modelo se essa ordem não existir na realidade.

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Exemplo de DataFrame com uma coluna categórica
data = {'Tamanho': ['Pequeno', 'Médio', 'Grande', 'Pequeno', 'Grande', 'Médio']}
df_label = pd.DataFrame(data)

print("DataFrame Original:")
display(df_label)

# Inicializa o LabelEncoder
le = LabelEncoder()

# Aplica o Label Encoding à coluna 'Tamanho'
df_label['Tamanho_Encoded'] = le.fit_transform(df_label['Tamanho'])

print("\nDataFrame após Label Encoding:")
display(df_label)

print("\nClasses mapeadas:")
for i, item in enumerate(le.classes_):
    print(f"{item} -> {i}")

DataFrame Original:

   Tamanho
0  Pequeno
1    Médio
2   Grande
3  Pequeno
4   Grande
5    Médio

DataFrame após Label Encoding:

   Tamanho  Tamanho_Encoded
0  Pequeno                2
1    Médio                1
2   Grande                0
3  Pequeno                2
4   Grande                0
5    Médio                1

Classes mapeadas:
Grande -> 0
Médio -> 1
Pequeno -> 2

### 2. Normalização (MinMaxScaler)

**O que é?**

`MinMaxScaler` é uma técnica de normalização que redimensiona os dados para um intervalo fixo, geralmente entre 0 e 1. Ele faz isso subtraindo o valor mínimo de cada feature e dividindo pelo intervalo (máximo - mínimo) da feature. A fórmula é:

`X_normalized = (X - X_min) / (X_max - X_min)`

**Quando usar?**

*   É muito útil para algoritmos que são sensíveis à escala dos dados, como redes neurais, SVMs (Support Vector Machines) com kernels baseados em distância e algoritmos baseados em distância como KNN (K-Nearest Neighbors).
*   Quando você deseja que todas as features contribuam igualmente para a distância calculada, independentemente de suas unidades ou magnitudes originais.
*   Quando a distribuição dos dados não é gaussiana ou quando a presença de **outliers** (valores atípicos - pontos de dados que se desviam significativamente de outras observações) é um fator, mas você deseja manter o formato da distribuição original (apenas redimensioná-la).

**Vantagens:**

*   Garantia de que todas as features estejam na mesma escala, o que pode melhorar o desempenho de muitos algoritmos de ML.
*   É simples de entender e implementar.
*   Preserva a forma da distribuição original dos dados.

**Desvantagens:**

*   É muito sensível a **outliers** (valores atípicos). Um único outlier pode distorcer significativamente o intervalo (Min-Max) e comprimir os dados "normais" em um intervalo muito pequeno.
*   Se houver novos dados fora do intervalo original (Min-Max), o scaler precisará ser reajustado, ou os novos dados não serão escalados corretamente.

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Exemplo de DataFrame com duas colunas numéricas em escalas diferentes
data = {
    'Idade': [25, 30, 35, 40, 60, 22, 55],
    'Salario_Anual': [30000, 45000, 50000, 70000, 120000, 28000, 90000]
}
df_minmax = pd.DataFrame(data)

print("DataFrame Original:")
display(df_minmax)

# Inicializa o MinMaxScaler
scaler = MinMaxScaler()

# Aplica a normalização às colunas 'Idade' e 'Salario_Anual'
df_minmax_scaled = df_minmax.copy()
df_minmax_scaled[['Idade_Scaled', 'Salario_Anual_Scaled']] = scaler.fit_transform(df_minmax[['Idade', 'Salario_Anual']])

print("\nDataFrame após MinMaxScaler:")
display(df_minmax_scaled)

print("\nValores mínimos e máximos após escalonamento:")
print(f"Idade Scaled: Min={df_minmax_scaled['Idade_Scaled'].min():.2f}, Max={df_minmax_scaled['Idade_Scaled'].max():.2f}")
print(f"Salario Anual Scaled: Min={df_minmax_scaled['Salario_Anual_Scaled'].min():.2f}, Max={df_minmax_scaled['Salario_Anual_Scaled'].max():.2f}")

DataFrame Original:

   Idade  Salario_Anual
0     25          30000
1     30          45000
2     35          50000
3     40          70000
4     60         120000
5     22          28000
6     55          90000

DataFrame após MinMaxScaler:

   Idade  Salario_Anual  Idade_Scaled  Salario_Anual_Scaled
0     25          30000      0.078947              0.021739
1     30          45000      0.210526              0.184783
2     35          50000      0.342105              0.239130
3     40          70000      0.473684              0.456522
4     60         120000      1.000000              1.000000
5     22          28000      0.000000              0.000000
6     55          90000      0.868421              0.673913

Valores mínimos e máximos após escalonamento:
Idade Scaled: Min=0.00, Max=1.00
Salario Anual Scaled: Min=0.00, Max=1.00

### 3. One-Hot Encoding

**O que é?**

`One-Hot Encoding` é uma técnica de pré-processamento usada para converter variáveis categóricas nominais (aquelas sem ordem intrínseca) em um formato numérico. Para cada categoria única em uma coluna, ele cria uma nova coluna binária (dummy variable) que contém 1 se a linha pertence a essa categoria e 0 caso contrário.

**Quando usar?**

*   É a técnica mais comum para variáveis categóricas nominais (ex: 'Vermelho', 'Azul', 'Verde'; 'Carro', 'Moto', 'Bicicleta').
*   É preferível ao `Label Encoding` para variáveis nominais, pois evita que o modelo interprete uma relação ordinal ou de magnitude entre as categorias, o que não existe na realidade.
*   Útil para algoritmos que esperam entrada numérica e assumem que valores maiores indicam uma ordem (ex: regressão linear, árvores de decisão).

**Vantagens:**

*   Não introduz uma ordem artificial entre as categorias.
*   Preserva a individualidade de cada categoria.
*   Modelos de ML podem interpretar facilmente as novas features binárias.

**Desvantagens:**

*   Aumenta a dimensionalidade do **dataset** (conjunto de dados), especialmente se a variável categórica tiver muitas categorias únicas. Isso pode levar ao problema de "maldição da dimensionalidade" e tornar o modelo mais lento ou propenso a **overfitting** (superajuste - quando um modelo de aprendizado de máquina aprende os detalhes e o ruído dos dados de treinamento a ponto de ter um desempenho ruim em dados novos e não vistos).
*   Pode causar multicolinearidade (quando uma coluna pode ser perfeitamente prevista por outras colunas), o que pode ser um problema para alguns modelos de regressão. Para mitigar isso, uma das colunas dummy pode ser removida (drop_first=True).

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

# Exemplo de DataFrame com uma coluna categórica nominal
data = {'Cor': ['Vermelho', 'Azul', 'Verde', 'Vermelho', 'Azul', 'Amarelo']}
df_onehot = pd.DataFrame(data)

print("DataFrame Original:")
display(df_onehot)

# Inicializa o OneHotEncoder
# handle_unknown='ignore' para lidar com categorias desconhecidas em dados futuros sem erro
# sparse_output=False para retornar um array denso do numpy (facilita a conversão para DataFrame)
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

# Aplica o One-Hot Encoding à coluna 'Cor'
# Cria um DataFrame a partir do resultado do encoding
df_encoded_cols = pd.DataFrame(encoder.fit_transform(df_onehot[['Cor']]),
                               columns=encoder.get_feature_names_out(['Cor']))

# Concatena as colunas codificadas com o DataFrame original
df_onehot_encoded = pd.concat([df_onehot, df_encoded_cols], axis=1)

print("\nDataFrame após One-Hot Encoding:")
display(df_onehot_encoded)

print("\nCategorias codificadas:")
print(encoder.get_feature_names_out(['Cor']))

DataFrame Original:

        Cor
0  Vermelho
1      Azul
2     Verde
3  Vermelho
4      Azul
5   Amarelo

DataFrame após One-Hot Encoding:

        Cor  Cor_Amarelo  Cor_Azul  Cor_Verde  Cor_Vermelho
0  Vermelho          0.0       0.0        0.0           1.0
1      Azul          0.0       1.0        0.0           0.0
2     Verde          0.0       0.0        1.0           0.0
3  Vermelho          0.0       0.0        0.0           1.0
4      Azul          0.0       1.0        0.0           0.0
5   Amarelo          1.0       0.0        0.0           0.0

Categorias codificadas:
['Cor_Amarelo' 'Cor_Azul' 'Cor_Verde' 'Cor_Vermelho']

### 4. RobustScaler

**O que é?**

`RobustScaler` é uma técnica de escalonamento que dimensiona os dados usando o intervalo interquartil (IQR), que é a diferença entre o terceiro quartil (Q3) e o primeiro quartil (Q1). Ele remove a mediana e escala os dados com base no IQR, tornando-o mais robusto a **outliers** (valores atípicos - pontos de dados que se desviam significativamente de outras observações) do que o `MinMaxScaler` ou `StandardScaler`.

A fórmula é:
`X_scaled = (X - Mediana) / IQR`

**Quando usar?**

*   É ideal para **datasets** (conjuntos de dados) que contêm muitos **outliers** (valores atípicos), pois a mediana e o IQR são menos afetados por valores extremos do que a média e o desvio padrão.
*   Quando a distribuição dos dados não é normal ou possui **caudas pesadas** (uma distribuição de dados que tem mais valores nas "caudas" - extremos - do que uma distribuição normal, indicando a presença de muitos valores extremos).
*   Assim como outros escalonadores, é útil para algoritmos que são sensíveis à escala das features.

**Vantagens:**

*   É robusto a **outliers** (valores atípicos), ou seja, menos impactado por valores extremos no **dataset** (conjunto de dados).
*   Preserva a forma da distribuição original dos dados, mas a torna mais compacta em torno da mediana.

**Desvantagens:**

*   Pode não produzir resultados tão bons quanto o `StandardScaler` ou `MinMaxScaler` se o **dataset** (conjunto de dados) não tiver **outliers** (valores atípicos) ou se a distribuição for aproximadamente normal, pois o IQR pode ser menos informativo do que o desvio padrão nesse cenário.
*   Os valores escalonados não ficam restritos a um intervalo específico (como [0, 1] no `MinMaxScaler`) ou a terem média zero e desvio padrão um exatos (como no `StandardScaler`), o que pode ser uma desvantagem para alguns algoritmos ou requisitos específicos.

In [ ]:
import pandas as pd
from sklearn.preprocessing import RobustScaler
import numpy as np

# Exemplo de DataFrame com outliers
data = {
    'Tempo_Atividade': [10, 15, 20, 25, 30, 100, 12, 18],
    'Valor_Transacao': [100, 150, 200, 250, 300, 5000, 120, 180]
}
df_robust = pd.DataFrame(data)

print("DataFrame Original:")
display(df_robust)

# Inicializa o RobustScaler
scaler = RobustScaler()

# Aplica o escalonamento robusto às colunas
df_robust_scaled = df_robust.copy()
df_robust_scaled[['Tempo_Atividade_Scaled', 'Valor_Transacao_Scaled']] = scaler.fit_transform(df_robust[['Tempo_Atividade', 'Valor_Transacao']])

print("\nDataFrame após RobustScaler:")
display(df_robust_scaled)

print("\nEstatísticas após escalonamento:")
print(f"Tempo_Atividade_Scaled: Mediana={df_robust_scaled['Tempo_Atividade_Scaled'].median():.2f}, IQR={df_robust_scaled['Tempo_Atividade_Scaled'].quantile(0.75) - df_robust_scaled['Tempo_Atividade_Scaled'].quantile(0.25):.2f}")
print(f"Valor_Transacao_Scaled: Mediana={df_robust_scaled['Valor_Transacao_Scaled'].median():.2f}, IQR={df_robust_scaled['Valor_Transacao_Scaled'].quantile(0.75) - df_robust_scaled['Valor_Transacao_Scaled'].quantile(0.25):.2f}")

### 5. Padronização (StandardScaler)

**O que é?**

`StandardScaler` é uma técnica de **padronização** (Standardization) que transforma os **dados** (data) para que tenham uma **média** (mean) de 0 e um **desvio padrão** (standard deviation) de 1. Ele faz isso subtraindo a média da **feature** (característica) e dividindo pelo desvio padrão da feature. A fórmula é:

`X_scaled = (X - média) / desvio_padrão`

**Quando usar?**

*   É muito útil para **algoritmos de aprendizado de máquina** (machine learning algorithms) que assumem que os **dados** (data) seguem uma **distribuição Gaussiana** (Gaussian distribution) ou que são sensíveis à escala das **features** (características), como **modelos lineares** (linear models - e.g., Regressão Linear, Regressão Logística), **redes neurais** (neural networks) e **Máquinas de Vetores de Suporte (SVMs)** (Support Vector Machines).
*   Quando as **features** (características) têm unidades de medida diferentes ou amplitudes muito variadas.

**Vantagens:**

*   Garante que todas as **features** (características) contribuam igualmente para o modelo, evitando que **features** (características) com valores maiores dominem o processo de aprendizado.
*   É menos sensível a **outliers** (valores atípicos - pontos de dados que se desviam significativamente de outras observações) do que o `MinMaxScaler`, pois usa a média e o desvio padrão, que são afetados, mas não tão drasticamente quanto o min-max.

**Desvantagens:**

*   Altera a distribuição dos **dados** (data) e não mantém os valores dentro de um intervalo específico (como o `MinMaxScaler` faz entre 0 e 1).
*   Para **datasets** (conjuntos de dados) com muitos **outliers** (valores atípicos), a média e o desvio padrão podem ser distorcidos, levando a um escalonamento menos eficaz. Nesses casos, o `RobustScaler` pode ser uma alternativa melhor.

**Exemplo:**

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
import numpy as np

# Exemplo de DataFrame com duas colunas numéricas em escalas e distribuições diferentes
data = {
    'Altura_cm': [160, 175, 182, 165, 190, 170, 178],
    'Peso_kg': [55, 70, 85, 60, 95, 68, 77]
}
df_standard = pd.DataFrame(data)

print("DataFrame Original:")
display(df_standard)

# Inicializa o StandardScaler
scaler = StandardScaler()

# Aplica a padronização às colunas 'Altura_cm' e 'Peso_kg'
df_standard_scaled = df_standard.copy()
df_standard_scaled[['Altura_Scaled', 'Peso_Scaled']] = scaler.fit_transform(df_standard[['Altura_cm', 'Peso_kg']])

print("\nDataFrame após StandardScaler:")
display(df_standard_scaled)

print("\nEstatísticas após escalonamento:")
print(f"Altura Scaled: Média={df_standard_scaled['Altura_Scaled'].mean():.2f}, Desvio Padrão={df_standard_scaled['Altura_Scaled'].std():.2f}")
print(f"Peso Scaled: Média={df_standard_scaled['Peso_Scaled'].mean():.2f}, Desvio Padrão={df_standard_scaled['Peso_Scaled'].std():.2f}")

DataFrame Original:

   Altura_cm  Peso_kg
0        160       55
1        175       70
2        182       85
3        165       60
4        190       95
5        170       68
6        178       77

DataFrame após StandardScaler:

   Altura_cm  Peso_kg  Altura_Scaled  Peso_Scaled
0        160       55      -1.506530    -1.380731
1        175       70       0.075326    -0.220917
2        182       85       0.813526     0.938897
3        165       60      -0.979244    -0.994126
4        190       95       1.657183     1.712106
5        170       68      -0.451959    -0.375559
6        178       77       0.391698     0.320330

Estatísticas após escalonamento:
Altura Scaled: Média=0.00, Desvio Padrão=1.08
Peso Scaled: Média=-0.00, Desvio Padrão=1.08