<a href="https://colab.research.google.com/github/JaCaRego/JaCaRego/blob/main/tratamento_dados_exercicio_mod10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Simulação de Dados Nulos
Primeiro, vamos criar uma cópia do nosso DataFrame e introduzir alguns valores `NaN` (Not a Number) para simular dados ausentes. Isso nos permitirá demonstrar como lidar com eles.

In [ ]:
import pandas as pd

# Define o caminho para o seu arquivo CSV baixado
# Você precisará atualizar este caminho após fazer o upload do arquivo para o Colab
# Exemplo: 'meu_arquivo.csv' se o arquivo estiver na raiz do seu ambiente Colab
csv_file_path = '/content/sample_data/california_housing_train.csv' # Atualize este caminho!

# Carrega o dataset
df = pd.read_csv(csv_file_path)
print(f'Dataset carregado com sucesso de: {csv_file_path}')

Dataset carregado com sucesso de: /content/sample_data/california_housing_train.csv

### Carregando o arquivo `ecommerce_preparados.csv`

In [ ]:
import pandas as pd

# Define o caminho para o seu arquivo CSV baixado 'ecommerce_preparados.csv'
# Certifique-se de que o arquivo foi carregado para o Colab ou especifique o caminho correto.
ecommerce_file_path = '/content/sample_data/ecommerce_preparados.csv' # Atualizado o caminho!

# Carrega o dataset
df_ecommerce = pd.read_csv(ecommerce_file_path)
print(f'Dataset "ecommerce_preparados.csv" carregado com sucesso de: {ecommerce_file_path}')

# Exibe as primeiras 5 linhas do novo DataFrame
display(df_ecommerce.head())

Dataset "ecommerce_preparados.csv" carregado com sucesso de: /content/sample_data/ecommerce_preparados.csv

,Unnamed: 0,Título,Nota,N_Avaliações,Desconto,Marca,Material,Gênero,Temporada,Review1,...,Nota_MinMax,N_Avaliações_MinMax,Desconto_MinMax,Preço_MinMax,Marca_Cod,Material_Cod,Temporada_Cod,Qtd_Vendidos_Cod,Marca_Freq,Material_Freq
0,0,Pijama Cirurgico Scrub Roupa Privativa Hospit...,4.0,273.0,NaN,toronto uniformes profissionais,poliéster,Sem gênero,não definido,"Preço justo , bem feito acabamento ok. Única s...",...,0.629630,0.029969,NaN,0.100645,781,122,1,1000.0,0.002274,0.117326
1,1,Kit 10 Cuecas Boxer Lupo Cueca Box Algodão Mas...,4.5,3034.0,18.0,lupo,algodão,Masculino,outono/inverno,As cuecas são boas; porém você percebe na cost...,...,0.814815,0.334178,0.213115,0.378585,463,25,3,10000.0,0.042292,0.176444
2,2,Kit Com 10 Cuecas Boxer Algodão Sem Costura Zo...,4.7,5682.0,20.0,zorba,algodão,Masculino,não definido,O tecido é bom e são confortáveis. Só que a nu...,...,0.888889,0.625937,0.245902,0.322329,838,25,1,50000.0,0.009095,0.176444
3,3,Kit 10 Cuecas Boxer Mash Algodão Cotton Box Or...,4.6,1700.0,22.0,mash,algodão,Masculino,primavera/verão,"As cuecas são boas, porém meu marido usa g e p...",...,0.851852,0.187197,0.278689,0.372617,494,25,7,10000.0,0.010914,0.176444
4,4,Kit 3 Short Jeans Feminino Cintura Alta Barato...,4.4,507.0,9.0,menina linda,jean,Feminino,primavera/verão,Estou encantada com essas peças!.\nOs shorts s...,...,0.777778,0.055751,0.065574,0.201767,509,74,7,1000.0,0.010005,0.025466

In [ ]:
import numpy as np

df_missing = df_ecommerce.copy()

# Introduzindo NaNs em algumas colunas para demonstração em df_ecommerce
df_missing.loc[df_missing.sample(frac=0.01).index, 'Nota'] = np.nan
df_missing.loc[df_missing.sample(frac=0.005).index, 'N_Avaliações'] = np.nan

print("DataFrame com NaNs simulados (df_ecommerce):")
display(df_missing.head())

DataFrame com NaNs simulados (df_ecommerce):

,Unnamed: 0,Título,Nota,N_Avaliações,Desconto,Marca,Material,Gênero,Temporada,Review1,...,Nota_MinMax,N_Avaliações_MinMax,Desconto_MinMax,Preço_MinMax,Marca_Cod,Material_Cod,Temporada_Cod,Qtd_Vendidos_Cod,Marca_Freq,Material_Freq
0,0,Pijama Cirurgico Scrub Roupa Privativa Hospit...,4.0,273.0,NaN,toronto uniformes profissionais,poliéster,Sem gênero,não definido,"Preço justo , bem feito acabamento ok. Única s...",...,0.629630,0.029969,NaN,0.100645,781,122,1,1000.0,0.002274,0.117326
1,1,Kit 10 Cuecas Boxer Lupo Cueca Box Algodão Mas...,4.5,3034.0,18.0,lupo,algodão,Masculino,outono/inverno,As cuecas são boas; porém você percebe na cost...,...,0.814815,0.334178,0.213115,0.378585,463,25,3,10000.0,0.042292,0.176444
2,2,Kit Com 10 Cuecas Boxer Algodão Sem Costura Zo...,4.7,5682.0,20.0,zorba,algodão,Masculino,não definido,O tecido é bom e são confortáveis. Só que a nu...,...,0.888889,0.625937,0.245902,0.322329,838,25,1,50000.0,0.009095,0.176444
3,3,Kit 10 Cuecas Boxer Mash Algodão Cotton Box Or...,4.6,1700.0,22.0,mash,algodão,Masculino,primavera/verão,"As cuecas são boas, porém meu marido usa g e p...",...,0.851852,0.187197,0.278689,0.372617,494,25,7,10000.0,0.010914,0.176444
4,4,Kit 3 Short Jeans Feminino Cintura Alta Barato...,4.4,507.0,9.0,menina linda,jean,Feminino,primavera/verão,Estou encantada com essas peças!.\nOs shorts s...,...,0.777778,0.055751,0.065574,0.201767,509,74,7,1000.0,0.010005,0.025466

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

### Identificando Valores Nulos
Podemos usar `.isnull()` em conjunto com `.sum()` para ver a contagem de valores nulos em cada coluna.

In [ ]:
print("Contagem de valores nulos por coluna:")
display(df_missing.isnull().sum())

Contagem de valores nulos por coluna:

Unnamed: 0                0
Título                    0
Nota                    654
N_Avaliações            648
Desconto               1325
Marca                     0
Material                867
Gênero                   79
Temporada                 0
Review1                 684
Review2                 845
Review3                 966
Qtd_Vendidos              0
Preço                   235
Nota_MinMax             640
N_Avaliações_MinMax     640
Desconto_MinMax        1325
Preço_MinMax            235
Marca_Cod                 0
Material_Cod              0
Temporada_Cod             0
Qtd_Vendidos_Cod        226
Marca_Freq                0
Material_Freq           867
dtype: int64

### Estratégias para Corrigir Dados Nulos com `fillna()`
O método `fillna()` do pandas é muito versátil. Aqui estão algumas das estratégias mais comuns:

In [ ]:
# 1. Preencher com a média (para colunas numéricas)
df_filled_mean = df_missing.copy()
mean_nota = df_filled_mean['Nota'].mean()
df_filled_mean['Nota'] = df_filled_mean['Nota'].fillna(mean_nota)

print(f"'Nota' preenchido com a média ({mean_nota:.2f}):")
display(df_filled_mean[['Nota']].head(10))
display(df_filled_mean.isnull().sum())

'Nota' preenchido com a média (4.56):

   Nota
0   4.0
1   4.5
2   4.7
3   4.6
4   4.4
5   4.7
6   4.9
7   4.5
8   4.3
9   4.4

Unnamed: 0                0
Título                    0
Nota                      0
N_Avaliações            648
Desconto               1325
Marca                     0
Material                867
Gênero                   79
Temporada                 0
Review1                 684
Review2                 845
Review3                 966
Qtd_Vendidos              0
Preço                   235
Nota_MinMax             640
N_Avaliações_MinMax     640
Desconto_MinMax        1325
Preço_MinMax            235
Marca_Cod                 0
Material_Cod              0
Temporada_Cod             0
Qtd_Vendidos_Cod        226
Marca_Freq                0
Material_Freq           867
dtype: int64

In [ ]:
# 2. Preencher com a mediana (menos sensível a outliers)
df_filled_median = df_missing.copy()
median_n_avaliacoes = df_filled_median['N_Avaliações'].median()
df_filled_median['N_Avaliações'] = df_filled_median['N_Avaliações'].fillna(median_n_avaliacoes)

print(f"'N_Avaliações' preenchido com a mediana ({median_n_avaliacoes:.0f}):")
display(df_filled_median[['N_Avaliações']].head(10))
display(df_filled_median.isnull().sum())

'N_Avaliações' preenchido com a mediana (27):

   N_Avaliações
0         273.0
1        3034.0
2        5682.0
3        1700.0
4         507.0
5          58.0
6          14.0
7          11.0
8          52.0
9        1326.0

Unnamed: 0                0
Título                    0
Nota                    654
N_Avaliações              0
Desconto               1325
Marca                     0
Material                867
Gênero                   79
Temporada                 0
Review1                 684
Review2                 845
Review3                 966
Qtd_Vendidos              0
Preço                   235
Nota_MinMax             640
N_Avaliações_MinMax     640
Desconto_MinMax        1325
Preço_MinMax            235
Marca_Cod                 0
Material_Cod              0
Temporada_Cod             0
Qtd_Vendidos_Cod        226
Marca_Freq                0
Material_Freq           867
dtype: int64

In [ ]:
# 3. Preencher com um valor específico (por exemplo, 0 para 'Nota')
df_filled_value = df_missing.copy()
df_filled_value['Nota'] = df_filled_value['Nota'].fillna(0)

print("'Nota' preenchido com 0:")
display(df_filled_value[['Nota']].head(10))
display(df_filled_value.isnull().sum())

'Nota' preenchido com 0:

   Nota
0   4.0
1   4.5
2   4.7
3   4.6
4   4.4
5   4.7
6   4.9
7   4.5
8   4.3
9   4.4

Unnamed: 0                0
Título                    0
Nota                      0
N_Avaliações            648
Desconto               1325
Marca                     0
Material                867
Gênero                   79
Temporada                 0
Review1                 684
Review2                 845
Review3                 966
Qtd_Vendidos              0
Preço                   235
Nota_MinMax             640
N_Avaliações_MinMax     640
Desconto_MinMax        1325
Preço_MinMax            235
Marca_Cod                 0
Material_Cod              0
Temporada_Cod             0
Qtd_Vendidos_Cod        226
Marca_Freq                0
Material_Freq           867
dtype: int64

### Outras Estratégias (`ffill`, `bfill`)

`ffill` (forward fill) preenche os valores nulos com o valor da linha anterior.
`bfill` (backward fill) preenche os valores nulos com o valor da próxima linha.

Essas estratégias são mais úteis para dados de séries temporais ou quando a ordem dos dados é significativa.

In [ ]:
df_ffill = df_missing.copy()
df_ffill['Nota'] = df_ffill['Nota'].ffill()

print("'Nota' preenchido com ffill:")
display(df_ffill[['Nota']].head(10))
display(df_ffill.isnull().sum())

'Nota' preenchido com ffill:

   Nota
0   4.0
1   4.5
2   4.7
3   4.6
4   4.4
5   4.7
6   4.9
7   4.5
8   4.3
9   4.4

Unnamed: 0                0
Título                    0
Nota                      0
N_Avaliações            648
Desconto               1325
Marca                     0
Material                867
Gênero                   79
Temporada                 0
Review1                 684
Review2                 845
Review3                 966
Qtd_Vendidos              0
Preço                   235
Nota_MinMax             640
N_Avaliações_MinMax     640
Desconto_MinMax        1325
Preço_MinMax            235
Marca_Cod                 0
Material_Cod              0
Temporada_Cod             0
Qtd_Vendidos_Cod        226
Marca_Freq                0
Material_Freq           867
dtype: int64

### Removendo Linhas com Valores Nulos (`dropna()`)
Em alguns casos, se a quantidade de dados nulos for pequena ou se a linha inteira não tiver utilidade sem aquele dado, podemos simplesmente remover as linhas que contêm valores nulos.

In [ ]:
df_dropped = df_missing.copy()

# Remove todas as linhas que contêm pelo menos um valor nulo
df_dropped.dropna(inplace=True)

print(f"Shape do DataFrame original com NaNs simulados: {df_missing.shape}")
print(f"Shape do DataFrame após remover linhas com NaNs: {df_dropped.shape}")
display(df_dropped.isnull().sum())

Shape do DataFrame original com NaNs simulados: (2199, 24)
Shape do DataFrame após remover linhas com NaNs: (292, 24)

Unnamed: 0             0
Título                 0
Nota                   0
N_Avaliações           0
Desconto               0
Marca                  0
Material               0
Gênero                 0
Temporada              0
Review1                0
Review2                0
Review3                0
Qtd_Vendidos           0
Preço                  0
Nota_MinMax            0
N_Avaliações_MinMax    0
Desconto_MinMax        0
Preço_MinMax           0
Marca_Cod              0
Material_Cod           0
Temporada_Cod          0
Qtd_Vendidos_Cod       0
Marca_Freq             0
Material_Freq          0
dtype: int64

### Salvando o DataFrame Tratado

Depois de remover as linhas com valores nulos, é uma boa prática salvar o DataFrame resultante para uso futuro ou para outras etapas de análise, garantindo que você não precise refazer o pré-processamento. Usaremos o método `to_csv()` para isso.

In [ ]:
# Salva o DataFrame df_dropped para um novo arquivo CSV
output_file_path = '/content/df_ecommerce_preparados_corrigido.csv'
df_dropped.to_csv(output_file_path, index=False) # index=False evita escrever o índice do DataFrame como uma coluna no CSV

print(f"DataFrame salvo com sucesso em: {output_file_path}")

NameError: name 'df_dropped' is not defined

A escolha da melhor estratégia depende do contexto dos seus dados e do tipo de análise que você pretende fazer. É crucial entender o porquê dos dados estarem faltando antes de decidir como preenchê-los ou removê-los.